# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 589f095cadd2b85ad2ccb873c4a9e5788b418e496b252a44bf3ba136bca9b961c6b4f81494eef5840cd99b68dcb95d8df39c712a75d35447322822a3dc35b240

test:
  secret_key_base: 6464fec327da4f5627ff5e9b95dd15e4e7e8f092411877871930aedecd4b861935f621490236e60d160d08f7f988d2f169beae318aadf64ee6afb61d9646125b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
